name: "CI"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - run: yarn lint
      - run: yarn test
      - run: yarn typecheck
      - run: yarn build
